import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Navbar from "./(components)/Navbar/Navbar";
import { SessionProviders } from "@/utils/providers";
import { SettingPageContextProvider } from "./(context)/SettingOpenContext";
import { AddNewContextProvider } from "./(context)/AddNewOpenContext";
import { TempolaryUserDataContextProvider } from "./(context)/TempolaryUserData";
import { MissingErrorFlagContextProvider } from "./(context)/MissingErrorFlagContext";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <SettingPageContextProvider>
          <TempolaryUserDataContextProvider>
            <AddNewContextProvider>
              <MissingErrorFlagContextProvider>
                <SessionProviders>
                  <Navbar/>
                  {children}
                </SessionProviders>
              </MissingErrorFlagContextProvider>
            </AddNewContextProvider>
          </TempolaryUserDataContextProvider>
        </SettingPageContextProvider>
      </body>
    </html>
  );
}
